"""Artifact engine: templates declare input contracts against engagement state.

Template frontmatter declares `requires_state` (dotted paths into
engagement.yaml). `--check-inputs` fails fast listing missing state. Bodies may
contain `<!-- state: <dotted.path> -->` markers that render deterministically;
everything else is filled by the agent from state.
"""
import re
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None

from . import registry

STATE_MARKER = re.compile(r"<!--\s*state:\s*([A-Za-z0-9_.]+)\s*-->")


def templates_dir(root=None):
    root = root or registry.find_toolkit_root()
    if root is None:
        raise FileNotFoundError("Cannot locate toolkit root. Set SA_KIT_ROOT.")
    return Path(root) / "templates"


def load_template(name, root=None):
    path = templates_dir(root) / f"{name}.md"
    if not path.is_file():
        available = sorted(p.stem for p in templates_dir(root).glob("*.md"))
        raise FileNotFoundError(f"no template '{name}'; available: {', '.join(available)}")
    text = path.read_text(encoding="utf-8")
    meta, err = registry.parse_frontmatter(text)
    if err:
        raise ValueError(f"{path.name}: {err}")
    body = text[text.find("\n---\n", 4) + 5:]
    return meta, body


def lookup(data, dotted):
    cur = data
    for part in dotted.split("."):
        if not isinstance(cur, dict) or part not in cur:
            return None
        cur = cur[part]
    return cur


def _is_empty(value):
    if value is None:
        return True
    if isinstance(value, str):
        return not value.strip() or value.strip().startswith("TODO")
    if isinstance(value, (list, dict)):
        return len(value) == 0
    return False


def check_inputs(meta, state):
    """Return list of missing/empty required state paths."""
    return [p for p in meta.get("requires_state", []) if _is_empty(lookup(state, p))]


def render_value(value):
    """Deterministic markdown for a state value."""
    if isinstance(value, list) and value and all(isinstance(i, dict) for i in value):
        keys = list(value[0].keys())
        lines = ["| " + " | ".join(keys) + " |", "|" + "---|" * len(keys)]
        for item in value:
            lines.append("| " + " | ".join(str(item.get(k, "")) for k in keys) + " |")
        return "\n".join(lines)
    if isinstance(value, list):
        return "\n".join(f"- {i}" for i in value)
    if isinstance(value, dict):
        return "\n".join(f"- **{k}**: {v}" for k, v in value.items())
    return str(value).strip()


def generate(name, engagement_path, out_dir=None, check_only=False, root=None):
    meta, body = load_template(name, root)
    state = yaml.safe_load(Path(engagement_path).read_text(encoding="utf-8")) or {}

    missing = check_inputs(meta, state)
    if missing:
        print(f"❌ template '{name}' is missing required state:")
        for p in missing:
            print(f"   - {p}")
        return 1
    if check_only:
        print(f"✅ all required state present for '{name}'.")
        return 0

    def replace(match):
        value = lookup(state, match.group(1))
        return render_value(value) if value is not None else match.group(0)

    rendered = STATE_MARKER.sub(replace, body)
    engagement_name = state.get("engagement", "engagement")
    header = (
        f"<!-- generated by sa-kit from {Path(engagement_path).name} on {date.today().isoformat()} -->\n"
        f"**DRAFT — CONFIDENTIAL** · engagement: {engagement_name}\n\n"
    )
    out_base = Path(out_dir) if out_dir else Path(engagement_path).parent / "artifacts"
    out_base.mkdir(parents=True, exist_ok=True)
    out_file = out_base / f"{name}.md"
    out_file.write_text(header + rendered, encoding="utf-8")
    print(f"Generated {out_file}")
    return 0
